version: "2.0"

services:
  web:
    build: .
    command: bash -c "node artifacts/db-reset.js && npm start"
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    image: mongo:latest
    expose:
      - "27017"
